"""First migration.

Revision ID: 0f21bf96ca55
Revises: 
Create Date: 2021-03-28 23:11:52.076392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f21bf96ca55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'duration')
    op.add_column('slides', sa.Column('duration', sa.Integer(), nullable=True))
    op.drop_column('slides', 'contact_now_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slides', sa.Column('contact_now_url', sa.VARCHAR(length=120), nullable=True))
    op.drop_column('slides', 'duration')
    op.add_column('services', sa.Column('duration', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
